server:
  port: 8080
spring:
  application:
    name: mybatis-study
  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml